# --------------------------------
# pmon3 config
# --------------------------------

# data dir, such as db data
data: "/etc/pmon3/data"
# logs dir
logs: "/var/log/pmond"
# kill processes on termintation
handle_interrupts: true
# wait [n] milliseconds before outputing list after running init/stop/restart/kill/drop/exec
cmd_exec_response_wait: 1500
# wait [n] milliseconds after connecting to IPC client before issuing commands
ipc_connection_wait: 200
