name: Testing

on:
  push:
    branches: [ "master", "develop" ]
    paths-ignore:
      - '**.md'
      - '**.sh'
      - '**.yml'
      - '**.yaml'
  pull_request:
    branches: [ "master", "develop" ]
  workflow_dispatch:

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Vet
      run: go vet ./...
      shell: bash

  build:
    name: Build
    needs: test
    strategy:
     matrix:
       os: [ ubuntu-latest, macOS-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Build TestServer
        run: go build -o bin/test_server test/test_server.go
        shell: bash

      - name: Run Pmond And Exec
        run: |
          PMON3_CONF=config.yml go run --race cmd/pmond/pmond.go &
          sleep 5
          PMON3_CONF=config.yml go run --race cmd/pmon3/pmon3.go exec bin/test_server
        shell: bash

      - name: Build amd64
        run: |
          GOARCH=amd64 go build -v ./...
        shell: bash

      - name: Build 386
        if: matrix.os != 'macOS-latest'
        run: |
          GOARCH=386 go build -v ./...
        shell: bash

      - name: Build arm64
        if: |
          matrix.os != 'macOS-latest'
        run: |
          GOARCH=arm64 go build -v ./...
        shell: bash

      - name: Build arm
        if: |
          matrix.os != 'macOS-latest'
        run: |
          GOARCH=arm go build -v ./...
        shell: bash

      - name: Finish
        run: |
          echo ":rocket: Build complete!" >> $GITHUB_STEP_SUMMARY
